version: "3.8"
services:
  database:
    image: mysql:latest
    container_name: database
    restart: always
    ports:
      - "6603:3306"
    env_file:
      - config.env
    expose:
      - "3306"
    volumes:
      - database-vol:/var/lib/mysql
  dashboard:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
volumes:
  database-vol:
